initial commit for the toaster and toaster demo component
fusionfabric/finastra-design-system pull request #251
Opened 2020-08-14 14:55 UTC by achilehero

Moved the toaster component used in DevPortal and UXP into FDS

2020-08-26 11:18 UTC, adrian-apetrei requested changes

2020-08-26 11:18 UTC, adrian-apetrei commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +    .message {
Text color is not visible in dark mode 
![image](https://user-images.githubusercontent.com/56310827/91296347-25526b80-e7a5-11ea-9ffb-97f77b1172db.png)

2020-08-26 11:18 UTC, adrian-apetrei commented on libs/angular-components/toaster/src/toaster.component.html
> +  <!-- <mat-icon dense *ngIf="toast.config.type === 'warning'" svgIcon="warning"></mat-icon>
remove commented code

2020-08-26 11:18 UTC, adrian-apetrei commented on apps/angular-test-app/src/app/components/toaster-demo/toaster-demo.component.scss
> +uxg-toaster-container {
Dark mode toggle is not accessible when toaster is open

2020-08-31 09:40 UTC, achilehero commented on libs/angular-components/toaster/src/toaster.component.html
> +  <!-- <mat-icon dense *ngIf="toast.config.type === 'warning'" svgIcon="warning"></mat-icon>
Removed

2020-08-31 09:50 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +    .message {
![image](https://user-images.githubusercontent.com/14956052/91707419-7341e780-eb88-11ea-8d19-2e3519204f8c.png)
fixed

2020-08-31 09:50 UTC, achilehero commented on apps/angular-test-app/src/app/components/toaster-demo/toaster-demo.component.scss
> +uxg-toaster-container {
Fixed

2020-08-31 09:57 UTC, adrian-apetrei approved these changes

2020-09-01 07:53 UTC, achilehero commented
> 
> 
> Looks like the toast is moving diagonally when entering and leaving, is it intended transition?
> 
> ![toast_diagonal_transition](https://user-images.githubusercontent.com/371041/91741865-9cc53800-ebb5-11ea-97fe-a9d8e56e3f1a.gif)

It's because the top margin is also animated, and it goes from 0 to the actual value. I can remove that if you think it's nicer to just be an horizontal slide. It's an easy one. Just let me know

2020-09-01 08:37 UTC, achilehero commented
Sure. I'll make it horizontal!

2020-09-01 09:19 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +@mixin uxg-toaster-theme($theme) {
I agree with the separation, but it seemed to me that in this particular case, since apart from the colors and text there are only a few spacing and sizing things present here, it wouldn't be worth splitting them into separate files. What do you think?

2020-09-01 10:33 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +        color: white;
If I use something like:
`&.type-warning .icon-container {
   background-color: mat-color($uxg-gold, 100);
      mat-icon {
        color: map-get($uxg-gold, default-contrast);
      }
    }`
I would get all the icons black, for all the backgrounds:
![image](https://user-images.githubusercontent.com/14956052/91839126-3a247880-ec57-11ea-97dd-f78e8354692e.png)

Is this what we want?

2020-09-01 13:18 UTC, rbordeanu commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +        color: white;
I don't really like this... :(  @ttalbot what other options do we have?

2020-09-01 13:59 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +        color: white;
In this case, I guess that making the icons area like [here](https://finastra.invisionapp.com/d/#/console/18537805/406609402/preview) would be better, then? I understand accessibility, but I don't like either how the icons look black on colored background.

2020-09-01 16:22 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +        color: white;
This is what we get after putting in the darker versions of secondary colors and using a lighter background:
![image](https://user-images.githubusercontent.com/14956052/91878802-7fad6980-ec88-11ea-949e-5094a727ddcf.png)

2020-09-01 16:49 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +@mixin uxg-toaster-theme($theme) {
Separated the files

2020-09-01 16:50 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +    box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.07), 0 1px 18px 0 rgba(0, 0, 0, 0.06), 0 3px 5px -1px rgba(0, 0, 0, 0.1);
I replaced the shadow with elevation

2020-09-04 09:31 UTC, achilehero commented on libs/angular-components/toaster/src/_toaster.theme.scss
> +        color: white;
So, @ttalbot, are we OK with the changes? If so, maybe we can try merging it.

2020-09-04 09:57 UTC, merged